# Пример scrape-конфига для Кладовки.
# Copyright 2026 Роман Сергеевич Кислов — Apache-2.0

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: kladovka
    metrics_path: /metrics
    http_sd_configs:
      - url: http://127.0.0.1:8000/internal/prometheus-sd
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [metrics_scheme]
        target_label: __scheme__
      - source_labels: [__meta_url]
        regex: .+
        action: keep
    # static_configs:
    #   - targets: ["127.0.0.1:8000"]
